services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: grabdy-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grabdy
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: grabdy-redis
    ports:
      - '6381:6379'

  inngest:
    image: inngest/inngest:latest
    container_name: grabdy-inngest
    command: inngest dev -u http://host.docker.internal:4000/api/inngest
    ports:
      - '8288:8288'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  pgdata:
  redisdata:
