/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsageRouteImport } from './routes/dashboard/usage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as DashboardSourcesIndexRouteImport } from './routes/dashboard/sources/index'
import { Route as DashboardIntegrationsIndexRouteImport } from './routes/dashboard/integrations/index'
import { Route as DashboardSourcesCollectionIdRouteImport } from './routes/dashboard/sources/$collectionId'
import { Route as DashboardApiMcpRouteImport } from './routes/dashboard/api/mcp'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api/keys'
import { Route as DashboardApiDocsRouteImport } from './routes/dashboard/api/docs'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/complete-account',
  path: '/complete-account',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSourcesIndexRoute = DashboardSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsIndexRoute =
  DashboardIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSourcesCollectionIdRoute =
  DashboardSourcesCollectionIdRouteImport.update({
    id: '/sources/$collectionId',
    path: '/sources/$collectionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApiMcpRoute = DashboardApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiDocsRoute = DashboardApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api/docs': typeof DashboardApiDocsRoute
  '/dashboard/api/keys': typeof DashboardApiKeysRoute
  '/dashboard/api/mcp': typeof DashboardApiMcpRoute
  '/dashboard/sources/$collectionId': typeof DashboardSourcesCollectionIdRoute
  '/dashboard/integrations/': typeof DashboardIntegrationsIndexRoute
  '/dashboard/sources/': typeof DashboardSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/api/docs': typeof DashboardApiDocsRoute
  '/dashboard/api/keys': typeof DashboardApiKeysRoute
  '/dashboard/api/mcp': typeof DashboardApiMcpRoute
  '/dashboard/sources/$collectionId': typeof DashboardSourcesCollectionIdRoute
  '/dashboard/integrations': typeof DashboardIntegrationsIndexRoute
  '/dashboard/sources': typeof DashboardSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/api/docs': typeof DashboardApiDocsRoute
  '/dashboard/api/keys': typeof DashboardApiKeysRoute
  '/dashboard/api/mcp': typeof DashboardApiMcpRoute
  '/dashboard/sources/$collectionId': typeof DashboardSourcesCollectionIdRoute
  '/dashboard/integrations/': typeof DashboardIntegrationsIndexRoute
  '/dashboard/sources/': typeof DashboardSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/chat'
    | '/dashboard/members'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/api/docs'
    | '/dashboard/api/keys'
    | '/dashboard/api/mcp'
    | '/dashboard/sources/$collectionId'
    | '/dashboard/integrations/'
    | '/dashboard/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/chat'
    | '/dashboard/members'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard'
    | '/dashboard/api/docs'
    | '/dashboard/api/keys'
    | '/dashboard/api/mcp'
    | '/dashboard/sources/$collectionId'
    | '/dashboard/integrations'
    | '/dashboard/sources'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/chat'
    | '/dashboard/members'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/api/docs'
    | '/dashboard/api/keys'
    | '/dashboard/api/mcp'
    | '/dashboard/sources/$collectionId'
    | '/dashboard/integrations/'
    | '/dashboard/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/sources/': {
      id: '/dashboard/sources/'
      path: '/sources'
      fullPath: '/dashboard/sources/'
      preLoaderRoute: typeof DashboardSourcesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations/': {
      id: '/dashboard/integrations/'
      path: '/integrations'
      fullPath: '/dashboard/integrations/'
      preLoaderRoute: typeof DashboardIntegrationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources/$collectionId': {
      id: '/dashboard/sources/$collectionId'
      path: '/sources/$collectionId'
      fullPath: '/dashboard/sources/$collectionId'
      preLoaderRoute: typeof DashboardSourcesCollectionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api/mcp': {
      id: '/dashboard/api/mcp'
      path: '/api/mcp'
      fullPath: '/dashboard/api/mcp'
      preLoaderRoute: typeof DashboardApiMcpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api/keys': {
      id: '/dashboard/api/keys'
      path: '/api/keys'
      fullPath: '/dashboard/api/keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api/docs': {
      id: '/dashboard/api/docs'
      path: '/api/docs'
      fullPath: '/dashboard/api/docs'
      preLoaderRoute: typeof DashboardApiDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApiDocsRoute: typeof DashboardApiDocsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardApiMcpRoute: typeof DashboardApiMcpRoute
  DashboardSourcesCollectionIdRoute: typeof DashboardSourcesCollectionIdRoute
  DashboardIntegrationsIndexRoute: typeof DashboardIntegrationsIndexRoute
  DashboardSourcesIndexRoute: typeof DashboardSourcesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApiDocsRoute: DashboardApiDocsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardApiMcpRoute: DashboardApiMcpRoute,
  DashboardSourcesCollectionIdRoute: DashboardSourcesCollectionIdRoute,
  DashboardIntegrationsIndexRoute: DashboardIntegrationsIndexRoute,
  DashboardSourcesIndexRoute: DashboardSourcesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
